name: Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/brytecam/*,github.com/100mslive/*
      GH_ACCESS_TOKEN: ${{ secrets.DOCKER_GIT_TOKEN }}
      HMS_ACCESS_KEY: ${{ secrets.HMS_ACCESS_KEY }}
      HMS_SECRET: ${{ secrets.HMS_SECRET }}
      TEST_ROOM_ID: ${{ secrets.TEST_ROOM_ID }}
      TEST_ROOM_NAME: ${{ secrets.TEST_ROOM_NAME }}
      TEST_MEETING_URL: ${{ secrets.TEST_MEETING_URL }}
      TEST_RTMP_URL: ${{ secrets.TEST_RTMP_URL }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          git submodule update --init --recursive

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install modules
        run: yarn
        working-directory: ./nodejs

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3

      - name: Configure git and Install deps for go-sdk
        run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          make prep-gh
        working-directory: ./go-sdk

      - name: Populate Room
        run: |
          ls -la
          echo -n '{
              "url": "' > config.json
          echo -n "$TEST_MEETING_URL" >> config.json
          echo '",
              "duration": 600,
              "count": 3,
              "subscribe_max_video": {
                  "high": 1,
                  "medium": 5,
                  "low": 0,
                  "priority": [
                      "medium",
                      "high"
                  ]
              },
              "subscribe_max_audio": 0,
              "join_rate": 5,
              "logger": {
                  "level": "panic",
                  "console_events": true,
                  "output": ""
              }
          }' >> config.json
          cat config.json
          make loadtest &
          populate_room_pid=$!
          sleep 100
          echo "started load-test pid=$populate_room_pid"
        working-directory: ./go-sdk

      - name: Run tests
        run: |
          yarn test
        working-directory: ./nodejs

      - name: Stop populate room
        run: kill $populate_room_pid
